-- V12: Seed common skill tags

INSERT INTO skill_tags (name, category) VALUES
-- Languages
('Java', 'language'),
('Python', 'language'),
('JavaScript', 'language'),
('TypeScript', 'language'),
('C', 'language'),
('C++', 'language'),
('C#', 'language'),
('Go', 'language'),
('Rust', 'language'),
('Kotlin', 'language'),
('Swift', 'language'),
('PHP', 'language'),
('Ruby', 'language'),
('Scala', 'language'),
('R', 'language'),
-- Frontend Frameworks
('Angular', 'framework'),
('React', 'framework'),
('Vue.js', 'framework'),
('Next.js', 'framework'),
('HTML', 'framework'),
('CSS', 'framework'),
('Tailwind CSS', 'framework'),
('Bootstrap', 'framework'),
-- Backend Frameworks
('Spring Boot', 'framework'),
('Node.js', 'framework'),
('Django', 'framework'),
('FastAPI', 'framework'),
('Express.js', 'framework'),
('Laravel', 'framework'),
('.NET', 'framework'),
-- Databases
('MySQL', 'database'),
('PostgreSQL', 'database'),
('MongoDB', 'database'),
('Redis', 'database'),
('Oracle', 'database'),
('SQL Server', 'database'),
('Elasticsearch', 'database'),
('Cassandra', 'database'),
-- Cloud & DevOps
('AWS', 'cloud'),
('Azure', 'cloud'),
('GCP', 'cloud'),
('Docker', 'devops'),
('Kubernetes', 'devops'),
('Jenkins', 'devops'),
('GitHub Actions', 'devops'),
('Terraform', 'devops'),
('Linux', 'devops'),
-- Tools & Concepts
('Git', 'tool'),
('REST API', 'concept'),
('GraphQL', 'concept'),
('Microservices', 'concept'),
('Machine Learning', 'concept'),
('Deep Learning', 'concept'),
('Data Analysis', 'concept'),
('Agile', 'concept'),
('System Design', 'concept'),
('Data Structures', 'concept'),
('Algorithms', 'concept');
